config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :shopping_lists

   root 'shopping_lists#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :shopping_list

end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    id = params[:id]
    @items = Item.where(shopping_list_id: id)
    #id = 1
    #params = (1)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    #@item = Item.find(params[:id])
  end

  # GET /items/new
  def new
  @item = Item.new
  end

  # GET /items/1/edit
  def edit

  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new
    id = params[:item][:shopping_list_id]
    new_item = params[:item][:item_name]
    store = params[:item][:store]
    @item.shopping_list_id=id
    @item.item_name=new_item
    @item.store=store
    @item.save

    respond_to do |format|
      if @item.save
        format.html { redirect_to shopping_lists_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    new_name = params[:item][:item_name]
    new_store = params[:item][:store]
    Item.find_by_item_name(@item.item_name).update(item_name: new_name, store: new_store)

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @item = Item.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:shopping_list_id)
    end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :edit, :update, :destroy]

  # GET /shopping_lists
  # GET /shopping_lists.json
  def index
    @shopping_lists = ShoppingList.all
    @items_in_this_list = []
  end

  # GET /shopping_lists/1
  # GET /shopping_lists/1.json
  def show

    redirect_to url_for(:controller => :items, :action => :index, :id => @shopping_list.id)

  end

  # GET /shopping_lists/new
  def new
    @shopping_list = ShoppingList.new

  end

  # GET /shopping_lists/1/edit
  def edit
  end

  # POST /shopping_lists
  # POST /shopping_lists.json
  def create
    @shopping_list = ShoppingList.create(name: params[:shopping_list][:name])

    respond_to do |format|
      if @shopping_list.save
        format.html { redirect_to shopping_lists_url, notice: 'Shopping list was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_list }
      else
        format.html { render :new }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_lists/1
  # PATCH/PUT /shopping_lists/1.json
  def update
    id = @shopping_list.id
    new_name = params[:shopping_list][:name]
    ShoppingList.find(id).update(name: new_name)

    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Name was successfully updated' }
      format.json { head :no_content }
    end
    #redirect_to :action => 'index'

  end

  # DELETE /shopping_lists/1
  # DELETE /shopping_lists/1.json
  def destroy
    id = @shopping_list.id
    items_to_delete = Item.where(shopping_list_id: id)
    items_to_delete.delete_all
    @shopping_list.destroy

    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Shopping list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  helper_method :get_items_for_list

  def get_items_for_list(list_id)
    i = Item.where(shopping_list_id: list_id).select(:item_name)

    if !@items_in_this_list.empty?
      size = @items_in_this_list.length
      for counter in 0..size
        @items_in_this_list.pop
      end

      i.each do |record|
      @items_in_this_list << record.item_name
      end
    else

      i.each do |record|
        @items_in_this_list << record.item_name
        end
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_shopping_list
      @shopping_list = ShoppingList.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @shopping_list = ShoppingList.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_list_params
      params.fetch(:shopping_list, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => "form-horizontal item" } do |f| %>

  <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :shopping_list_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :shopping_list_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:shopping_list_id) %>
  </div>
  <div class="form-group">
    <%= f.label :item_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :item_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:item_name) %>
  </div>
  <div class="form-group">
    <%= f.label :store, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :store, :class => 'form-control' %>
    </div>
    <%=f.error_span(:store) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                      shopping_lists_url, :action => 'index', :class => 'btn btn-default'%>
    </div>
  </div>

<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:shopping_list_id) %></th>
      <th><%= model_class.human_attribute_name(:item_name) %></th>
      <th><%= model_class.human_attribute_name(:store) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.shopping_list_id %></td>
        <td><%= item.item_name %></td>
        <td><%= item.store %></td>
        <td><%=l item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:shopping_list_id) %>:</strong></dt>
  <dd><%= @item.shopping_list_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:item_name) %>:</strong></dt>
  <dd><%= @item.item_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store) %>:</strong></dt>
  <dd><%= @item.store %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shopping_lists_url, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
                     edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    item_path(@item),
                    :method => 'delete',
                     :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                     :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "AllMyShoppingLists" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AllMyShoppingLists</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!--<li>Keep track of your shopping with ease!</li> -->
            <!--<li><%= link_to "Link1", "/path1"  %></li> -->
            <!--<li><%= link_to "Link2", "/path2"  %></li> -->
            <!--<li><%= link_to "Link3", "/path3"  %></li> -->
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Share your Lists:</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Facebook", "#"  %></li>
              <li><%= link_to "Twitter", "#"  %></li>
              <li><%= link_to "Instagram", "#"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shopping_lists/_form.html.erb
<%= form_for @shopping_list, :html => { :class => "form-horizontal shopping_list" } do |f| %>

  <% if @shopping_list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@shopping_list.errors.count, "error") %> prohibited this shopping_list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @shopping_list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shopping_lists_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/shopping_lists/edit.html.erb
<%- model_class = ShoppingList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shopping_lists/index.html.erb
<%- model_class = ShoppingList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shopping_lists.each do |shopping_list| %>

      <tr>
        <td><%= link_to shopping_list.id, shopping_list_path(shopping_list) %></td>
        <td><strong><%= shopping_list.name %></strong></td>
        <td><%=l shopping_list.created_at %></td>
        <td>
          <%= link_to "show", {:controller => "shopping_lists", :action => "show", :id => shopping_list.id, :class => 'btn btn-primary'}%>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shopping_list_path(shopping_list), :class => 'btn btn-default btn-xs'  %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shopping_list_path(shopping_list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      <% get_items_for_list(shopping_list.id) %>
      <tr><td colspan="4"><% @items_in_this_list.each do |item|%>
        <ul><li><%=item %></li>
        </ul>
        <%end%>
            </td></tr>
     <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_shopping_list_path,
            :class => 'btn btn-primary' %>

app/views/shopping_lists/new.html.erb
<%- model_class = ShoppingList -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shopping_lists/show.html.erb
<%- model_class = ShoppingList -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table>
  <tr><td style="width:60px"><strong><%= model_class.human_attribute_name(:name) %>:</strong></td>
  <td><%= @shopping_list.name %></td></tr>
</table>
<br>
<table>
  <thead><th>Item</th><th>Store</th><th></th></thead>
  <tbody>
   <% for counter in 0..@item_name_arr.length %>
   <tr><td style="width:130px"><%= @item_name_arr[counter] %></td> <td style="width:130px"><%= @store_arr[counter] %></td></tr>
     <%end%>
  </tbody>

</table>

<br>
<br>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shopping_lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shopping_list_path(@shopping_list), :class => 'btn btn-default' %>

app/views/shopping_lists/update.html.erb
<h1>Update View</h1>